# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: result.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='result.proto',
    package='result',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0cresult.proto\x12\x06result\"w\n\x11SaveResultRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12\x13\n\x0btask_status\x18\x03 \x01(\t\x12\x10\n\x08\x66inished\x18\x04 \x01(\x08\x12\x15\n\rcrawl_results\x18\x05 \x01(\t\"$\n\x12SaveResultResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32M\n\x06Result\x12\x43\n\nSaveResult\x12\x19.result.SaveResultRequest\x1a\x1a.result.SaveResultResponseb\x06proto3'
)

_SAVERESULTREQUEST = _descriptor.Descriptor(
    name='SaveResultRequest',
    full_name='result.SaveResultRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='customer_id', full_name='result.SaveResultRequest.customer_id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='task_id', full_name='result.SaveResultRequest.task_id', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='task_status', full_name='result.SaveResultRequest.task_status', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='finished', full_name='result.SaveResultRequest.finished', index=3,
            number=4, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='crawl_results', full_name='result.SaveResultRequest.crawl_results', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=24,
    serialized_end=143,
)

_SAVERESULTRESPONSE = _descriptor.Descriptor(
    name='SaveResultResponse',
    full_name='result.SaveResultResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='status', full_name='result.SaveResultResponse.status', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=145,
    serialized_end=181,
)

DESCRIPTOR.message_types_by_name['SaveResultRequest'] = _SAVERESULTREQUEST
DESCRIPTOR.message_types_by_name['SaveResultResponse'] = _SAVERESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveResultRequest = _reflection.GeneratedProtocolMessageType('SaveResultRequest', (_message.Message,), {
    'DESCRIPTOR': _SAVERESULTREQUEST,
    '__module__': 'result_pb2'
    # @@protoc_insertion_point(class_scope:result.SaveResultRequest)
})
_sym_db.RegisterMessage(SaveResultRequest)

SaveResultResponse = _reflection.GeneratedProtocolMessageType('SaveResultResponse', (_message.Message,), {
    'DESCRIPTOR': _SAVERESULTRESPONSE,
    '__module__': 'result_pb2'
    # @@protoc_insertion_point(class_scope:result.SaveResultResponse)
})
_sym_db.RegisterMessage(SaveResultResponse)

_RESULT = _descriptor.ServiceDescriptor(
    name='Result',
    full_name='result.Result',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=183,
    serialized_end=260,
    methods=[
        _descriptor.MethodDescriptor(
            name='SaveResult',
            full_name='result.Result.SaveResult',
            index=0,
            containing_service=None,
            input_type=_SAVERESULTREQUEST,
            output_type=_SAVERESULTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_RESULT)

DESCRIPTOR.services_by_name['Result'] = _RESULT

# @@protoc_insertion_point(module_scope)
