"""init

Revision ID: 8efa2b9dcc87
Revises: 
Create Date: 2020-12-08 10:22:43.545415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8efa2b9dcc87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.Column('url_nested_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_state', sa.String(length=30), server_default='readying', nullable=True),
    sa.Column('failure_url_ids', sa.ARRAY(sa.Integer()), server_default='{}', nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_tasks_create_time'), 'crawl_tasks', ['create_time'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_subtask_id'), 'crawl_tasks', ['subtask_id'], unique=False)
    op.create_index(op.f('ix_crawl_tasks_update_time'), 'crawl_tasks', ['update_time'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('url_address', sa.String(length=1024), nullable=False),
    sa.Column('http_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('current_url', sa.String(length=1024), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('har_uuid', sa.String(length=128), nullable=True),
    sa.Column('screenshot_id', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_create_time'), 'results', ['create_time'], unique=False)
    op.create_index(op.f('ix_results_subtask_id'), 'results', ['subtask_id'], unique=False)
    op.create_index(op.f('ix_results_update_time'), 'results', ['update_time'], unique=False)
    op.create_index(op.f('ix_results_url_id'), 'results', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_url_id'), table_name='results')
    op.drop_index(op.f('ix_results_update_time'), table_name='results')
    op.drop_index(op.f('ix_results_subtask_id'), table_name='results')
    op.drop_index(op.f('ix_results_create_time'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_crawl_tasks_update_time'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_subtask_id'), table_name='crawl_tasks')
    op.drop_index(op.f('ix_crawl_tasks_create_time'), table_name='crawl_tasks')
    op.drop_table('crawl_tasks')
    # ### end Alembic commands ###
