"""初始化

Revision ID: 4a243739ef84
Revises: 
Create Date: 2021-01-19 18:22:08.458531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a243739ef84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('url_address', sa.String(length=1024), nullable=False),
    sa.Column('http_code', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('current_url', sa.String(length=1024), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('har_uuid', sa.String(length=128), nullable=True),
    sa.Column('screenshot_id', sa.String(length=128), nullable=True),
    sa.Column('cookies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('wappalyzer_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('callback_failure_msg', sa.Text(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_create_time'), 'results', ['create_time'], unique=False)
    op.create_index(op.f('ix_results_subtask_id'), 'results', ['subtask_id'], unique=False)
    op.create_index(op.f('ix_results_update_time'), 'results', ['update_time'], unique=False)
    op.create_index(op.f('ix_results_url_id'), 'results', ['url_id'], unique=False)
    op.create_table('schedule_task_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('schedule_task_status', sa.String(length=255), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('crawl_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_task_records_create_time'), 'schedule_task_records', ['create_time'], unique=False)
    op.create_index(op.f('ix_schedule_task_records_task_id'), 'schedule_task_records', ['task_id'], unique=False)
    op.create_table('servers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(length=128), nullable=True),
    sa.Column('server_address', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('weight', sa.Integer(), server_default='3', nullable=True),
    sa.Column('load', sa.String(length=20), server_default='0.1', nullable=True),
    sa.Column('spider_type', sa.String(length=20), server_default='splash', nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_address')
    )
    op.create_index(op.f('ix_servers_create_time'), 'servers', ['create_time'], unique=False)
    op.create_index(op.f('ix_servers_update_time'), 'servers', ['update_time'], unique=False)
    op.create_table('sub_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_task_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('assigned_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('delivery_failure_msg', sa.Text(), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_tasks_create_time'), 'sub_tasks', ['create_time'], unique=False)
    op.create_index(op.f('ix_sub_tasks_schedule_task_id'), 'sub_tasks', ['schedule_task_id'], unique=False)
    op.create_index(op.f('ix_sub_tasks_update_time'), 'sub_tasks', ['update_time'], unique=False)
    op.create_table('task_url',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('url_id', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_url_create_time'), 'task_url', ['create_time'], unique=False)
    op.create_index(op.f('ix_task_url_task_id'), 'task_url', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_url_update_time'), 'task_url', ['update_time'], unique=False)
    op.create_index(op.f('ix_task_url_url_id'), 'task_url', ['url_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('task_status', sa.String(length=255), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('schedule_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crawl_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_create_time'), 'tasks', ['create_time'], unique=False)
    op.create_index(op.f('ix_tasks_customer_id'), 'tasks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tasks_update_time'), 'tasks', ['update_time'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_address'), 'urls', ['address'], unique=True)
    op.create_index(op.f('ix_urls_create_time'), 'urls', ['create_time'], unique=False)
    op.create_index(op.f('ix_urls_update_time'), 'urls', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_update_time'), table_name='urls')
    op.drop_index(op.f('ix_urls_create_time'), table_name='urls')
    op.drop_index(op.f('ix_urls_address'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_tasks_update_time'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_create_time'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_url_url_id'), table_name='task_url')
    op.drop_index(op.f('ix_task_url_update_time'), table_name='task_url')
    op.drop_index(op.f('ix_task_url_task_id'), table_name='task_url')
    op.drop_index(op.f('ix_task_url_create_time'), table_name='task_url')
    op.drop_table('task_url')
    op.drop_index(op.f('ix_sub_tasks_update_time'), table_name='sub_tasks')
    op.drop_index(op.f('ix_sub_tasks_schedule_task_id'), table_name='sub_tasks')
    op.drop_index(op.f('ix_sub_tasks_create_time'), table_name='sub_tasks')
    op.drop_table('sub_tasks')
    op.drop_index(op.f('ix_servers_update_time'), table_name='servers')
    op.drop_index(op.f('ix_servers_create_time'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_schedule_task_records_task_id'), table_name='schedule_task_records')
    op.drop_index(op.f('ix_schedule_task_records_create_time'), table_name='schedule_task_records')
    op.drop_table('schedule_task_records')
    op.drop_index(op.f('ix_results_url_id'), table_name='results')
    op.drop_index(op.f('ix_results_update_time'), table_name='results')
    op.drop_index(op.f('ix_results_subtask_id'), table_name='results')
    op.drop_index(op.f('ix_results_create_time'), table_name='results')
    op.drop_table('results')
    # ### end Alembic commands ###
