"""加入网站编码

Revision ID: 5b189e0161ee
Revises: 1569921cac58
Create Date: 2021-04-19 10:32:15.201074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b189e0161ee'
down_revision = '1569921cac58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('charset', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'charset')
    # ### end Alembic commands ###
