"""新增网站图标字段

Revision ID: 71bf761944f8
Revises: 4a243739ef84
Create Date: 2021-01-21 16:39:56.687514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bf761944f8'
down_revision = '4a243739ef84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('favicon_link', sa.String(length=1024), nullable=True))
    op.add_column('results', sa.Column('favicon_md5', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'favicon_md5')
    op.drop_column('results', 'favicon_link')
    # ### end Alembic commands ###
