"""增加extra客户端额外数据

Revision ID: b3bd5bc9e4e3
Revises: 71bf761944f8
Create Date: 2021-01-25 17:52:28.285830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bd5bc9e4e3'
down_revision = '71bf761944f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('extra_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'extra_data')
    # ### end Alembic commands ###
